
import Header from "@/components/ui/Header";
import "./globals.css";

import { Titillium_Web, Abel } from 'next/font/google'
import Menu from "@/components/ui/Menu";

export const headingFont = Titillium_Web({
  weight: ["200", "400", "600"],
  subsets: ["latin"]
})

const AbelFont = Abel({
  weight: ["400"],
  subsets: ["latin"]
})


export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body
        className={`${AbelFont.className} antialiased`}
      >
        <Header />
        {children}
        {/* <div className="h-[80vh] overflow-auto">
        </div> */}
        <Menu />
      </body>
    </html>
  );
}
